# Generated by Django 2.2.5 on 2021-05-30 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210530_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
